export const BackModule = [
  { id: "back_001", type: "yes_no_toggle" },
  { id: "back_002", type: "yes_no_toggle" },
  { id: "back_003", type: "datetime" },
  { id: "back_004", type: "radio_group", options: ["Hours", "Days", "Weeks"] },
  { id: "back_005", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "back_006", type: "yes_no_toggle" },
  { id: "back_007", type: "radio_group", options: ["Constant", "Comes and goes"] },
  { id: "back_008", type: "radio_group", options: ["Better", "Same", "Worse"] },
  { id: "back_009", type: "yes_no_toggle" },
  { id: "back_010", type: "yes_no_toggle" },
  { id: "back_011", type: "radio_group", options: ["Neck", "Upper back", "Lower back", "Tailbone", "Diffuse"] },
  { id: "back_012", type: "radio_group", options: ["Middle", "Left", "Right", "Both sides"] },
  { id: "back_013", type: "radio_group", options: ["Sharp", "Dull", "Burning", "Cramping", "Like a heavy pressure", "Not sure"] },
  { id: "back_014", type: "range" },
  { id: "back_015", type: "yes_no_toggle" },
  { id: "back_016", type: "yes_no_toggle" },
  { id: "back_017", type: "body_map" },
  { id: "back_018", type: "yes_no_toggle" },
  { id: "back_019", type: "yes_no_toggle" },
  { id: "back_020", type: "yes_no_toggle" },
  { id: "back_021", type: "yes_no_toggle" },
  { id: "back_022", type: "yes_no_toggle" },
  { id: "back_023", type: "yes_no_toggle" },
  { id: "back_024", type: "yes_no_toggle" },
  { id: "back_025", type: "yes_no_toggle" },
  { id: "back_026", type: "yes_no_toggle" },
  { id: "back_027", type: "yes_no_toggle" },
  { id: "back_028", type: "yes_no_toggle" },
  { id: "back_029", type: "yes_no_toggle" },
  { id: "back_030", type: "yes_no_toggle" },
  { id: "back_031", type: "yes_no_toggle" },
  { id: "back_032", type: "yes_no_toggle" },
  { id: "back_033", type: "yes_no_toggle" },
  { id: "back_034", type: "yes_no_toggle" },
  { id: "back_035", type: "yes_no_toggle" },
];