// Cardiac Module
export const CardiacModule = [
  { id: "prom_cardpain", type: "yes_no_toggle" },
  { id: "confirm_cardpain", type: "radio_group", options: ["Remove", "Proceed"] },
  { id: "card_pain01", type: "radio_group", options: ["Resting", "Physical activity", "Eating"] },
  { id: "card_pain02A", type: "yes_no_toggle" },
  { id: "card_pain03A", type: "yes_no_toggle" },
  { id: "card_pain04A", type: "yes_no_toggle" },
  { id: "card_pain05A", type: "radio_group", options: ["Left arm", "Right arm", "Both arms", "No"] },
  { id: "card_pain06A", type: "yes_no_toggle" },
  { id: "card_pain07A", type: "yes_no_toggle" },
  { id: "card_pain08A", type: "radio_group", options: ["Worse", "About the same"] },
  { id: "card_pain09A", type: "radio_group", options: ["Worse", "About the same"] },
  { id: "card_pain10A", type: "yes_no_toggle" },
  { id: "card_pain11A", type: "yes_no_toggle" },
  { id: "card_pain02B", type: "yes_no_toggle" },
  { id: "card_pain03B", type: "yes_no_toggle" },
  { id: "card_pain04B", type: "yes_no_toggle" },
  { id: "card_pain05B", type: "radio_group", options: ["Left arm", "Right arm", "Both arms", "No"] },
  { id: "card_pain06B", type: "yes_no_toggle" },
  { id: "card_pain07B", type: "yes_no_toggle" },
  { id: "card_pain08B", type: "radio_group", options: ["Worse", "About the same"] },
  { id: "card_pain09B", type: "radio_group", options: ["Worse", "About the same"] },
  { id: "card_pain10B", type: "yes_no_toggle" },
  { id: "card_pain11B", type: "yes_no_toggle" },
  { id: "card_01", type: "yes_no_toggle" },
  { id: "card_011", type: "radio_group", options: ["One side", "Both sides"] },
  { id: "card_012", type: "radio_group", options: ["Right", "Left"] },
  { id: "card_013", type: "yes_no_toggle" },
  { id: "card_014", type: "yes_no_toggle" },
  { id: "card_015", type: "yes_no_toggle" },
  { id: "card_016", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "card_02", type: "yes_no_toggle" },
  { id: "card_03", type: "yes_no_toggle" }
];