// Chest Module
export const ChestModule = [
  { id: "chest_001", type: "yes_no_toggle" },
  { id: "chest_002", type: "chest_map" },
  { id: "chest_002p", type: "chest_map" },
  { id: "chest_003", type: "text" },
  { id: "chest_004", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "chest_005", type: "yes_no_toggle" },
  { id: "chest_005p", type: "yes_no_toggle" },
  { id: "chest_006", type: "body_map" },
  { id: "chest_006p", type: "body_map" },
  { id: "chest_007", type: "yes_no_toggle" },
  { id: "chest_007p", type: "yes_no_toggle" },
  { id: "chest_008", type: "radio_group", options: ["Sharp", "Dull", "Burning", "Cramping", "Like a heavy pressure", "Not sure"] },
  { id: "chest_009", type: "range" },
  { id: "chest_009p", type: "range" },
  { id: "chest_010", type: "radio_group", options: ["One continuous episode", "Multiple episodes"] },
  { id: "chest_011", type: "number" },
  { id: "chest_012", type: "radio_group", options: ["Minutes", "Hours"] },
  { id: "chest_013", type: "radio_group", options: ["Constant", "Comes and goes"] },
  { id: "chest_013p", type: "radio_group", options: ["Constant", "Comes and goes"] },
  { id: "chest_014", type: "radio_group", options: ["Resting", "Physical activity", "Eating"] },
  { id: "chest_015", type: "yes_no_toggle" },
  { id: "chest_016", type: "yes_no_toggle" },
  { id: "chest_017", type: "yes_no_toggle" },
  { id: "chest_018", type: "yes_no_toggle" },
  { id: "chest_019", type: "yes_no_toggle" },
  { id: "chest_020", type: "yes_no_toggle" },
  { id: "chest_021", type: "yes_no_toggle" },
  { id: "chest_022", type: "yes_no_toggle" },
  { id: "chest_023", type: "yes_no_toggle" },
  { id: "chest_024", type: "yes_no_toggle" },
  { id: "chest_025", type: "yes_no_toggle" },
  { id: "chest_026", type: "yes_no_toggle" },
  { id: "chest_027", type: "yes_no_toggle" },
  { id: "chest_028", type: "yes_no_toggle" },
  { id: "chest_029", type: "yes_no_toggle" },
];