// Dizzy Module
export const DizzyModule = [
  { id: "dizzy_001", type: "yes_no_toggle" },
  { id: "dizzy_002", type: "radio_group", options: ["Spinning sensation (like the room is moving)","Feeling like you might faint","Unsteady when walking","Just feel 'off' or not well"]},
  { id: "dizzy_003", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "dizzy_004", type: "radio_group", options: ["Today", "Yesterday", "Days ago"] },
  { id: "dizzy_005", type: "radio_group", options: ["Seconds", "Minutes", "Hours", "Days", "Constant"] },
  { id: "dizzy_006", type: "radio_group", options: ["Single", "Recurrent"] },
  { id: "dizzy_007", type: "radio_group", options: ["Better", "Same", "Worse"] },
  { id: "dizzy_008", type: "yes_no_toggle" },
  { id: "dizzy_009", type: "yes_no_toggle" },
  { id: "dizzy_010", type: "yes_no_toggle" },
  { id: "dizzy_011", type: "yes_no_toggle" },
  { id: "dizzy_012", type: "yes_no_toggle" },
  { id: "dizzy_013", type: "yes_no_toggle" },
  { id: "dizzy_014", type: "yes_no_toggle" },
  { id: "dizzy_015", type: "yes_no_toggle" },
  { id: "dizzy_016", type: "yes_no_toggle" },
  { id: "dizzy_017", type: "yes_no_toggle" },
  { id: "dizzy_018", type: "yes_no_toggle" },
  { id: "dizzy_019", type: "yes_no_toggle" },
  { id: "dizzy_020", type: "yes_no_toggle" },
  { id: "dizzy_021", type: "yes_no_toggle" },
  { id: "dizzy_022", type: "yes_no_toggle" },
  { id: "dizzy_023", type: "yes_no_toggle" },
  { id: "dizzy_024", type: "yes_no_toggle" },
];