// Eye Module
export const EyeModule = [
  { id: "eye_001", type: "yes_no_toggle" },
  { id: "eye_002", type: "yes_no_toggle" },
  { id: "eye_003", type: "yes_no_toggle" },
  { id: "eye_004", type: "yes_no_toggle" },
  { id: "eye_005", type: "yes_no_toggle" },
  { id: "eye_006", type: "yes_no_toggle" },
  { id: "eye_007", type: "radio_group", options: ["Right", "Left", "Both"] },
  { id: "eye_008", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "eye_009", type: "radio_group", options: ["Today", "Yesterday", "Days ago"] },
  { id: "eye_010", type: "radio_group", options: ["Hours", "Days"] },
  { id: "eye_011", type: "radio_group", options: ["Better", "Same", "Worse"] },
  { id: "eye_012", type: "radio_group", options: ["Itchy", "Burning", "Gritty", "Sharp", "Deep", "Not sure"] },
  { id: "eye_013", type: "range" },
  { id: "eye_014", type: "yes_no_toggle" },
  { id: "eye_015", type: "yes_no_toggle" },
  { id: "eye_016", type: "yes_no_toggle" },
  { id: "eye_017", type: "yes_no_toggle" },
  { id: "eye_018", type: "yes_no_toggle" },
  { id: "eye_019", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "eye_020", type: "radio_group", options: ["None", "Watery", "Sticky", "Pus"] },
  { id: "eye_021", type: "yes_no_toggle" },
  { id: "eye_022", type: "yes_no_toggle" },
  { id: "eye_023", type: "yes_no_toggle" },
  { id: "eye_024", type: "yes_no_toggle" },
  { id: "eye_025", type: "yes_no_toggle" },
  { id: "eye_026", type: "yes_no_toggle" },
  { id: "eye_027", type: "yes_no_toggle" },
  { id: "eye_028", type: "yes_no_toggle" },
  { id: "eye_029", type: "radio_group", options: ["Today", "Yesterday", "Days ago"] },
  { id: "eye_030", type: "yes_no_toggle" },
  { id: "eye_031", type: "yes_no_toggle" },
  { id: "eye_032", type: "yes_no_toggle" },
  { id: "eye_033", type: "yes_no_toggle" },
  { id: "eye_034", type: "yes_no_toggle" },
];