// GastroIntestinal Module
export const GIModule = [
  { id: "gi_001", type: "yes_no_toggle" },
  { id: "gi_002", type: "abdomen_map" },
  { id: "gi_003", type: "range" },
  { id: "gi_004", type: "radio_group", options: ["Sharp", "Dull", "Burning", "Cramping", "Not sure"] },
  { id: "gi_005", type: "radio_group", options: ["Constant", "Comes and goes"] },
  { id: "gi_006", type: "yes_no_toggle" },
  { id: "gi_007", type: "number" },
  { id: "gi_008", type: "yes_no_toggle" },
  { id: "gi_009", type: "number" },
  { id: "gi_010", type: "yes_no_toggle" },
  { id: "gi_011", type: "yes_no_toggle" },
  { id: "gi_012", type: "yes_no_toggle" },
  { id: "gi_013", type: "yes_no_toggle" },
  { id: "gi_014", type: "yes_no_toggle" },
  { id: "gi_015", type: "colour", colourType: "vomit", options: ["Food", "Clear fluid", "Yellow-green", "Dark like coffee grounds", "Fresh blood", "Not sure"] },
  { id: "gi_016", type: "number" },
  { id: "gi_017", type: "yes_no_toggle" },
  { id: "gi_018", type: "yes_no_toggle" },
  { id: "gi_019", type: "radio_group", options: ["Hours", "Days"] },
  { id: "gi_020", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "gi_021", type: "yes_no_toggle" },
  { id: "gi_022", type: "yes_no_toggle" },
  { id: "gi_023", type: "body_map" },
  { id: "gi_024", type: "yes_no_toggle" },
  { id: "gi_025", type: "yes_no_toggle" },
  { id: "gi_026", type: "yes_no_toggle" },
  { id: "gi_027", type: "yes_no_toggle" },
  { id: "gi_028", type: "radio_group", options: ["Normal", "Loose or watery", "Difficult to pass motion"] },
  { id: "gi_029", type: "number" },
  { id: "gi_030", type: "yes_no_toggle" },
  { id: "gi_031", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "gi_032", type: "radio_group", options: ["Today", "Yesterday", "Days ago"] },
  { id: "gi_033", type: "yes_no_toggle" },
  { id: "gi_034", type: "yes_no_toggle" },
  { id: "gi_035", type: "yes_no_toggle" },
  { id: "gi_036", type: "yes_no_toggle" },
  { id: "gi_037", type: "yes_no_toggle" },
  { id: "gi_038", type: "yes_no_toggle" },
  { id: "gi_039", type: "yes_no_toggle" },
  { id: "gi_040", type: "yes_no_toggle" },
  { id: "gi_041", type: "yes_no_toggle" },
];
