// Head Module
export const HeadModule = [
  { id: "head_001", type: "yes_no_toggle" },
  { id: "head_002", type: "date" },
  { id: "head_003", type: "radio_group", options: ["Sudden (like a thunderclap)", "Gradual"] },
  { id: "head_004", type: "yes_no_toggle" },
  { id: "head_005", type: "yes_no_toggle" },
  { id: "head_006", type: "radio_group", options: ["Single", "Recurrent"] },
  { id: "head_007", type: "radio_group", options: ["Better", "Same", "Worse"] },
  { id: "head_008", type: "head_map" },
  { id: "head_009", type: "radio_group", options: ["Throbbing", "Pressure", "Tight", "Sharp", "Not sure"] },
  { id: "head_010", type: "range" },
  { id: "head_011", type: "yes_no_toggle" },
  { id: "head_012", type: "yes_no_toggle" },
  { id: "head_013", type: "yes_no_toggle" },
  { id: "head_014", type: "yes_no_toggle" },
  { id: "head_015", type: "yes_no_toggle" },
  { id: "head_016", type: "yes_no_toggle" },
  { id: "head_017", type: "yes_no_toggle" },
  { id: "head_018", type: "yes_no_toggle" },
];