// Med Module
export const MedModule = [
  { id: "med_001", type: "yes_no_toggle" },
  { id: "med_002", type: "yes_no_toggle" },
  { id: "med_003", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "med_004", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "med_005", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "med_006", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "med_007", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "med_008", type: "yes_no_toggle" },
  { id: "med_009", type: "yes_no_toggle" },
  { id: "med_010", type: "yes_no_toggle" },
  { id: "med_011", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "med_012", type: "text" },
  { id: "med_013", type: "radio_group", options: ["Rash", "Swelling", "Breathing difficulty", "Dizziness", "Not sure", "Other"] },
  { id: "med_014", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "med_015", type: "yes_no_toggle" },
  { id: "med_016", type: "yes_no_toggle" },
  { id: "med_017", type: "yes_no_toggle" },
  { id: "med_018", type: "yes_no_toggle" },
  { id: "med_019", type: "yes_no_toggle" },
  { id: "med_020", type: "yes_no_toggle" },
  { id: "med_021", type: "yes_no_toggle" },
];