// Neurological Module
export const NeuroModule = [
  { id: "prom_headache", type: "yes_no_toggle" },
  { id: "confirm_headache", type: "radio_group", options: ["Remove", "Proceed"] },
  { id: "neuro_head01", type: "head_map" },
  { id: "neuro_head02", type: "number" },
  { id: "neuro_head03", type: "radio_group", options: ["Sudden (like a thunderclap)", "Gradual"] },
  { id: "neuro_head04", type: "radio_group", options: ["Single", "Recurrent"] },
  { id: "neuro_head05", type: "range" },
  { id: "neuro_head06", type: "yes_no_toggle" },
  { id: "neuro_head061", type: "yes_no_toggle" },
  { id: "neuro_head07", type: "radio_group", options: ["Better", "Same", "Worse"] },
  { id: "neuro_head08", type: "radio_group", options: ["Throbbing", "Pressure", "Tight", "Sharp", "Not sure"] },
  { id: "neuro_head09", type: "yes_no_toggle" },
  { id: "neuro_head10", type: "yes_no_toggle" },
  { id: "neuro_head11", type: "yes_no_toggle" },
  { id: "neuro_head12", type: "yes_no_toggle" },
  { id: "neuro_head13", type: "yes_no_toggle" },
  { id: "neuro_head14", type: "yes_no_toggle" },
  { id: "neuro_head15", type: "yes_no_toggle" },
  { id: "neuro_head16", type: "yes_no_toggle" },
  { id: "neuro_head161", type: "number" },
  { id: "neuro_head162", type: "radio_group", options: ["Fall", "Hit head on object", "Road traffic accident", "Sports injury", "Assault", "Other"] },

  { id: "prom_dizziness", type: "yes_no_toggle" },
  { id: "confirm_dizziness", type: "radio_group", options: ["Remove", "Proceed"] },
  { id: "neuro_dizz01", type: "radio_group", options: ["Spinning sensation (like seasickness or like the room is moving)", "Feeling like you might faint", "Unsteady when walking", "Just feeling off or not well"] },
  { id: "neuro_dizz02", type: "number" },
  { id: "neuro_dizz03", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "neuro_dizz04", type: "radio_group", options: ["Better", "Same", "Worse"] },
  { id: "neuro_dizz05", type: "radio_group", options: ["All the time", "Comes and goes"] },
  { id: "neuro_dizz06", type: "yes_no_toggle" },
  { id: "neuro_dizz07", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "neuro_dizz08", type: "radio_group", options: ["Yes", "No", "Don't know"] },
  { id: "neuro_dizz081", type: "yes_no_toggle" },
  { id: "neuro_dizz09", type: "yes_no_toggle" },

  { id: "prom_weakness", type: "yes_no_toggle" },
  { id: "confirm_weakness", type: "radio_group", options: ["Remove", "Proceed"] },
  { id: "neuro_weak01", type: "radio_group", options: ["Generally weak", "Weak in certain parts of body"] },
  { id: "neuro_weak011", type: "yes_no_toggle" },
  { id: "neuro_weak012", type: "radio_group", options: ["Right side", "Left side", "Both sides"] },
  { id: "neuro_weak02", type: "body_map" },
  { id: "neuro_weak03", type: "radio_group", options: ["Yes (right side)", "Yes (left side)", "No"] },
  { id: "neuro_weak031", type: "body_map" },
  { id: "neuro_weak04", type: "yes_no_toggle" },
  { id: "neuro_weak05", type: "yes_no_toggle" },
  { id: "neuro_weak06", type: "yes_no_toggle" },
  { id: "neuro_weak07", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "neuro_weak08", type: "number" },
  { id: "neuro_weak09", type: "yes_no_toggle" },

  { id: "prom_syncope", type: "yes_no_toggle" },
  { id: "confirm_syncope", type: "radio_group", options: ["Remove", "Proceed"] },
  { id: "neuro_sync01", type: "number" },
  { id: "neuro_sync02", type: "radio_group", options: ["Completely lost consciousness", "Nearly fainted"] },
  { id: "neuro_sync021", type: "radio_group", options: ["Seconds", "Minutes", ">5 minutes", "Not sure"] },
  { id: "neuro_sync03", type: "radio_group", options: ["Standing", "Sitting", "Lying down"] },
  { id: "neuro_sync031", type: "yes_no_toggle" },
  { id: "neuro_sync04", type: "yes_no_toggle" },
  { id: "neuro_sync05", type: "yes_no_toggle" },
  { id: "neuro_sync06", type: "yes_no_toggle" },
  { id: "neuro_sync07", type: "yes_no_toggle" },
  { id: "neuro_sync08", type: "yes_no_toggle" },
  { id: "neuro_sync09", type: "yes_no_toggle" },
  { id: "neuro_sync10", type: "yes_no_toggle" },
  { id: "neuro_sync11", type: "yes_no_toggle" },
  { id: "neuro_sync12", type: "yes_no_toggle" },
  { id: "neuro_sync13", type: "yes_no_toggle" },
  { id: "neuro_sync14", type: "yes_no_toggle" },
  { id: "neuro_sync15", type: "yes_no_toggle" },
  { id: "neuro_sync16", type: "yes_no_toggle" },
  { id: "neuro_sync17", type: "radio_group", options: ["Quick recovery", "Took time"] },
  { id: "neuro_sync18", type: "yes_no_toggle" },
  { id: "neuro_sync19", type: "yes_no_toggle" },
  { id: "neuro_sync20", type: "yes_no_toggle" },
  { id: "neuro_sync21", type: "yes_no_toggle" },

  { id: "neuro_01", type: "yes_no_toggle" },
  { id: "neuro_02", type: "yes_no_toggle" },
  { id: "neuro_03", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "neuro_031", type: "radio_group", options: ["One continuous episode", "Multiple episodes"] },
  { id: "neuro_032", type: "number" },
  { id: "neuro_033", type: "number" }
];