export const PainModule = [
  { id: "pain_git_01", type: "abdomen_map" },
  { id: "pain_git_02", type: "number" },
  { id: "pain_git_03", type: "yes_no_toggle" },
  { id: "pain_git_031A", type: "range" },
  { id: "pain_git_031B", type: "range" },
  { id: "pain_git_04", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "pain_git_05", type: "radio_group", options: ["One continuous episode", "Multiple episodes"] },
  { id: "pain_git_051", type: "number" },
  { id: "pain_git_052", type: "number" },
  { id: "pain_git_053", type: "range" },
  { id: "pain_git_06", type: "radio_group", options: ["Sharp", "Dull", "Burning", "Cramping", "Tearing", "Like a heavy pressure", "Not sure"] },
  { id: "pain_git_07A", type: "radio_group", options: ["Constant", "Comes and goes"] },
  { id: "pain_git_07B", type: "radio_group", options: ["Constant", "Comes and goes"] },
  { id: "pain_card_01", type: "chest_map" },
  { id: "pain_card_02", type: "number" },
  { id: "pain_card_03", type: "yes_no_toggle" },
  { id: "pain_card_031A", type: "range" },
  { id: "pain_card_031B", type: "range" },
  { id: "pain_card_04", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "pain_card_05", type: "radio_group", options: ["One continuous episode", "Multiple episodes"] },
  { id: "pain_card_051", type: "number" },
  { id: "pain_card_052", type: "number" },
  { id: "pain_card_053", type: "range" },
  { id: "pain_card_06", type: "radio_group", options: ["Sharp", "Dull", "Burning", "Cramping", "Tearing", "Like a heavy pressure", "Not sure"] },
  { id: "pain_card_07A", type: "radio_group", options: ["Constant", "Comes and goes"] },
  { id: "pain_card_07B", type: "radio_group", options: ["Constant", "Comes and goes"] }
];