// Respiratory Module
export const RespModule = [
  { id: "resp_001", type: "yes_no_toggle" },
  { id: "resp_002", type: "yes_no_toggle" },
  { id: "resp_003", type: "yes_no_toggle" },
  { id: "resp_004", type: "yes_no_toggle" },
  { id: "resp_005", type: "colour", colourType: "sputum", options: ["Clear", "Yellow","Green","White","Pinkish"],},
  { id: "resp_006", type: "yes_no_toggle" },
  { id: "resp_007", type: "yes_no_toggle" },
  { id: "resp_008", type: "yes_no_toggle" },
  { id: "resp_009", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "resp_010", type: "radio_group", options: ["Hours", "Days"] },
  { id: "resp_011", type: "yes_no_toggle" },
  { id: "resp_012", type: "yes_no_toggle" },
  { id: "resp_013", type: "yes_no_toggle" },
  { id: "resp_014", type: "yes_no_toggle" },
  { id: "resp_015", type: "yes_no_toggle" },
  { id: "resp_016", type: "yes_no_toggle" },
  { id: "resp_017", type: "yes_no_toggle" },
  { id: "resp_018", type: "yes_no_toggle" },
];