// Syncope Module
export const SyncopeModule = [
  { id: "syncope_001", type: "yes_no_toggle" },
  { id: "syncope_002", type: "yes_no_toggle" },
  { id: "syncope_003", type: "yes_no_toggle" },
  { id: "syncope_004", type: "radio_group", options: ["<3h", "3–6h", "6–12h", ">12h"] },
  { id: "syncope_005", type: "radio_group", options: ["Sudden", "Gradual"] },
  { id: "syncope_006", type: "radio_group", options: ["Seconds", "Minutes", ">5 minutes", "Not sure"] },
  { id: "syncope_007", type: "radio_group", options: ["Rapid", "Took time"] },
  { id: "syncope_008", type: "yes_no_toggle" },
  { id: "syncope_009", type: "radio_group", options: ["Standing", "Sitting", "Lying down"] },
  { id: "syncope_010", type: "radio_group", options: ["Resting", "Physical activity", "After activity"] },
  { id: "syncope_011", type: "yes_no_toggle" },
  { id: "syncope_012", type: "yes_no_toggle" },
  { id: "syncope_013", type: "yes_no_toggle" },
  { id: "syncope_014", type: "yes_no_toggle" },
  { id: "syncope_015", type: "yes_no_toggle" },
  { id: "syncope_016", type: "yes_no_toggle" },
  { id: "syncope_017", type: "yes_no_toggle" },
  { id: "syncope_018", type: "yes_no_toggle" },
  { id: "syncope_019", type: "yes_no_toggle" },
  { id: "syncope_020", type: "yes_no_toggle" },
  { id: "syncope_021", type: "yes_no_toggle" },
  { id: "syncope_022", type: "yes_no_toggle" },
  { id: "syncope_023", type: "yes_no_toggle" },
  { id: "syncope_024", type: "yes_no_toggle" },
  { id: "syncope_025", type: "yes_no_toggle" },
  { id: "syncope_026", type: "yes_no_toggle" },
  { id: "syncope_027", type: "yes_no_toggle" },
  { id: "syncope_028", type: "yes_no_toggle" },
  { id: "syncope_029", type: "yes_no_toggle" },
  { id: "syncope_030", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "syncope_031", type: "radio_group", options: ["Yes", "No", "Not sure"] },
  { id: "syncope_032", type: "yes_no_toggle" },
  { id: "syncope_033", type: "yes_no_toggle" },
  { id: "syncope_034", type: "yes_no_toggle" },
  { id: "syncope_035", type: "yes_no_toggle" },
  { id: "syncope_036", type: "yes_no_toggle" },
  { id: "syncope_037", type: "yes_no_toggle" },
  { id: "syncope_038", type: "yes_no_toggle" },
  { id: "syncope_039", type: "yes_no_toggle" },
  { id: "syncope_040", type: "yes_no_toggle" },
  { id: "syncope_041", type: "yes_no_toggle" },
  { id: "syncope_042", type: "yes_no_toggle" },
];