export const ChiefComplaints1 = [
  { name: "Fever", icon: "🤒" },
  { name: "Shortness of breath", icon: "🌬️" },
  { name: "Headache", icon: "🤕" },
  { name: "Chest pain", icon: "❤️" },
  { name: "Dizziness", icon: "😵" },
  { name: "Eye problem", icon: "👁️" },
  { name: "Nausea/Vomiting", icon: "🤮" },
  { name: "Cough/Sore throat", icon: "😷" },
  { name: "Diarrhoea", icon: "🚽" },
  { name: "Stomach/Abdominal pain", icon: "🤢" },
  { name: "Weakness or numbness", icon: "🧘" },
  { name: "Fainting/Blackout", icon: "😴" },
  { name: "Muscle, Back, or Joint pain", icon: "🦵" },
  { name: "Feeling generally unwell", icon: "🤧" },
  { name: "Skin problem", icon: "🧼" },
  { name: "Problem with passing urine", icon: "💧" },
];

import { 
  Thermometer, 
  Wind,          // instead of Lungs
  Brain, 
  HeartPulse,
  Orbit,
  Eye,
  Activity,
  Accessibility,
  Moon,
  Bone,
  Frown,
  Grid,
  Droplet,
  Droplets,
  Ear,
  Bandage,
  RotateCcw,
  ArrowDown
} from 'lucide-react';

export const ChiefComplaints = [
  { name: "Fever", icon: Thermometer },
  { name: "Shortness of breath", icon: Wind },
  { name: "Headache", icon: Brain },
  { name: "Chest pain", icon: HeartPulse },
  { name: "Dizziness", icon: Orbit },
  { name: "Eye problem", icon: Eye },
  { name: "Nausea/Vomiting", icon: RotateCcw },
  { name: "Cough/Sore throat", icon: Wind },
  { name: "Diarrhoea", icon: ArrowDown },
  { name: "Stomach/Abdominal pain", icon: Activity },
  { name: "Weakness or numbness", icon: Accessibility },
  { name: "Fainting/Blackout", icon: Moon },
  { name: "Muscle, Back, or Joint pain", icon: Bone },
  { name: "Feeling generally unwell", icon: Frown },
  { name: "Skin problem", icon: Grid },
  { name: "Problem with passing urine", icon: Droplet },
  { name: "Bleeding", icon: Droplets },
  { name: "Injury", icon: Bandage },
  { name: "Ear, Nose, or Throat problem", icon: Ear },
];