// ChestPainGeneral.js
export const ChestPainGeneral = [
  { id: "chestpain_now", label: "Are you still having pain right now?", type: "yes_no_toggle",
  },
  { id: "chestpain_firststart", label: "When did the pain first start?", type: "number",
  },
  { id: "chestpain_timesinceonset", label: "When did the pain start?", type: "radio_group", options: ["<3h", "3-6h", "6-12h", ">12h"],
  },
  { id: "chestpain_duration", label: "How long have you had this pain?", type: "number",
  },
  { id: "chestpain_timecourse", label: "Is the pain constant, or does it come and go?", type: "radio_group", options: ["Constant", "Comes and goes"],
  },
  { id: "chestpain_episodes", label: "Have you had one episode of pain, or multiple episodes?", type: "radio_group", options: ["One continuous episode", "Multiple episodes"],
  },
  { id: "chestpain_episodenum", label: "How many episodes have you had?", type: "number",
    showIf: (a) => a.chestpain_episodes === "Multiple episodes"
  },
  { id: "chestpain_episodeduration", label: "How long does each episode usually last?", type: "radio_group", options: ["Minutes", "Hours"],
    showIf: (a) => a.chestpain_episodes === "Multiple episodes"
  },
  { id: "chestpain_onset", label: "Did the pain start suddenly or gradually?", type: "radio_group", options: ["Sudden", "Gradual"],
  },
  { id: "chestpain_maxatonset", label: "Did the pain become very severe right away when it started?", type: "yes_no_toggle",
  },
  { id: "chestpain_location", label: "Where do you feel the pain?", type: "body_map",
  },
  { id: "chestpain_radiation", label: "Does the pain spread anywhere else?", type: "yes_no_toggle",
  },
  { id: "chestpain_radiationlocation", label: "Where does the pain spread to?", type: "body_map",
    showIf: (a) => a.chestpain_radiation === "Yes"
  },
  { id: "chestpain_classicradiation", label: "Does the pain spread to your arm, jaw, or back?", type: "yes_no_toggle",
    showIf: (a) => a.chestpain_radiation === "Yes"
  },
  { id: "chestpain_character", label: "Can you describe the pain?", type: "radio_group", options: ["Sharp", "Dull", "Burning", "Cramping", "Like a heavy pressure", "Not sure"],
  },
  { id: "chestpain_score", label: "How bad is the pain now?", type: "range",
  },
  { id: "chestpain_worst", label: "Is this the worst chest pain you have ever had?", type: "yes_no_toggle",
  },
  { id: "chestpain_activityonset", label: "What were you doing when the pain started?", type: "radio_group", options: ["Resting", "Physical activity", "Eating"],
  },
  { id: "chestpain_exertional", label: "Did it start or worsen with physical activity?", type: "yes_no_toggle",
  },
  { id: "chestpain_atrest", label: "Did it happen while resting?", type: "yes_no_toggle",
  },
  { id: "chestpain_gi1", label: "Does eating make the pain worse?", type: "yes_no_toggle",
  },
  { id: "chestpain_resp", label: "Does deep breathing or coughing make the pain worse?", type: "yes_no_toggle",
  },
  { id: "chestpain_gi3", label: "Does coughing or moving make the pain worse?", type: "yes_no_toggle",
  },
  { id: "chestpain_positional", label: "Does changing position affect the pain?", type: "yes_no_toggle",
  },
  { id: "chestpain_cardiac2", label: "Does sitting forward make the pain better?", type: "yes_no_toggle",
  },
  { id: "chestpain_cardiac3", label: "Does the pain improve with rest?", type: "yes_no_toggle",
  },
  { id: "chestpain_antacidrelief", label: "Does taking antacids help the pain?", type: "yes_no_toggle",
  },
  { id: "chestpain_palpation", label: "Does pressing on the chest make the pain worse?", type: "yes_no_toggle",
  },
];